src/src/Models/Organization.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace src.Models
{
    public class Organization : BaseEntity
    {
        public Organization()
        {
            this.thumbUrl = "/images/blank-building.png";
            
        }
        public Guid organizationId { get; set; }
        [Display(Name = "Organization Name")]
        [Required]
        [StringLength(100)]
        public string organizationName { get; set; }
        [StringLength(200)]
        [Display(Name = "Description")]
        public string description { get; set; }
        [StringLength(255)]
        [Display(Name = "Thumb URL")]
        public string thumbUrl { get; set; }

        //refer to Application User
        public string organizationOwnerId { get; set; }

    }
}

src/src/Controllers/Api/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using src.Data;
using src.Models;

namespace src.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/Config")]
    [Authorize]
    public class ConfigController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ConfigController(ApplicationDbContext context)
        {
            _context = context;
        }

        // POST: api/Config/ChangePersonalProfile
        [HttpPost("ChangePersonalProfile")]
        public async Task<IActionResult> ChangePersonalProfile([FromBody] ApplicationUser applicationUser)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                ApplicationUser appUser = _context.ApplicationUser.Where(x => x.Id.Equals(applicationUser.Id)).FirstOrDefault();
                Employees employees = _context.Employees.Where(x => x.IdNumber == appUser.IdNumber).FirstOrDefault();
                appUser.FullName = applicationUser.FullName;
                appUser.PhoneNumber = applicationUser.PhoneNumber;
                appUser.Address = applicationUser.Address;
                appUser.BirthDate = applicationUser.BirthDate;

                employees.FullName = appUser.FullName;
                employees.PhoneNumber = applicationUser.PhoneNumber;
                employees.Address = applicationUser.Address;
                employees.BirthDate = applicationUser.BirthDate;

                _context.Employees.Update(employees);
                _context.Update(appUser);

                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Edit data success.", appUser });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }


        }
    }
}

src/src/Controllers/Api/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using src.Data;
using src.Models;

namespace src.Controllers.Api
{
    [Produces("application/json")]
    [Route("api/Organization")]
    [Authorize]
    public class OrganizationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrganizationController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Organization
        [HttpGet("{applicationUserId}")]
        public IActionResult GetOrganization([FromRoute]string applicationUserId)
        {
            return Json(new { data = _context.Organization.Where(x => x.organizationOwnerId.Equals(applicationUserId)).OrderByDescending(x => x.CreateAt).ToList() });
        }


        // POST: api/Organization
        [HttpPost]
        public async Task<IActionResult> PostOrganization([FromBody] Organization organization)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                if (organization.organizationId == Guid.Empty)
                {
                    organization.organizationId = Guid.NewGuid();
                    _context.Organization.Add(organization);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Add new data success." });
                }
                else
                {
                    _context.Update(organization);

                    await _context.SaveChangesAsync();

                    return Json(new { success = true, message = "Edit data success." });
                }
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }

           
        }

        // DELETE: api/Organization/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteOrganization([FromRoute] Guid id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var organization = await _context.Organization.SingleOrDefaultAsync(m => m.organizationId == id);
                if (organization == null)
                {
                    return NotFound();
                }

                _context.Organization.Remove(organization);
                await _context.SaveChangesAsync();

                return Json(new { success = true, message = "Delete success." });
            }
            catch (Exception ex)
            {

                return Json(new { success = false, message = ex.Message });
            }

           
        }

        private bool OrganizationExists(Guid id)
        {
            return _context.Organization.Any(e => e.organizationId == id);
        }
    }
}

src/src/Controllers/ConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using src.Data;
using src.Models;

namespace src.Controllers
{
    [Authorize]
    public class ConfigController : BaseDotnetDeskController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public ConfigController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(Guid org)
        {
            if (org == Guid.Empty)
            {
                org = Guid.NewGuid();
                //return NotFound();
            }
            ApplicationUser appUser = await _userManager.GetUserAsync(User);

            Organization organization = _context.Organization.Where(x => x.organizationId.Equals(org)).FirstOrDefault();
            ViewData["org"] = org;
            return View(organization);
        }

        public IActionResult AddEditIndex(Guid org, string id)
        {
            if (id == null)
            {
                Employees employees = new Employees();
                return View(employees);
            }
            else
            {
                return View(_context.Employees.Where(x => x.IdNumber.Equals(id)).FirstOrDefault());
            }

        }

        public async Task<IActionResult> Organization()
        {
            ApplicationUser appUser = await _userManager.GetUserAsync(User);
            return View(appUser);
        }

        public async Task<IActionResult> AddEditOrganization(Guid id)
        {
            
            if (Guid.Empty == id)
            {
                ApplicationUser appUser = await _userManager.GetUserAsync(User);
                Organization org = new Organization();
                org.organizationOwnerId = appUser.Id;
                return View(org);
            }
            else
            {
                return View(_context.Organization.Where(x => x.organizationId.Equals(id)).FirstOrDefault());
            }

        }

        public async Task<IActionResult> UserProfile(Guid org)
        {
            //ApplicationUser appUser = await _userManager.GetUserAsync(User);
            ////return View(appUser);
            //Organization organization = _context.Organization.Where(x => x.organizationId.Equals(org)).FirstOrDefault();
            //ViewData["org"] = org;
            //return View(organization);

            ApplicationUser appUser = await _userManager.GetUserAsync(User);
            
            Organization organization = _context.Organization.Where(x => x.organizationId.Equals(org)).FirstOrDefault();
            ViewData["org"] = org;
            return View(appUser);
        }

        public async Task<IActionResult> UserUploadPhoto()
        {
            ApplicationUser appUser = await _userManager.GetUserAsync(User);
            return View(appUser);
        }

        public async Task<IActionResult> PersonalProfile()
        {
            ApplicationUser appUser = await _userManager.GetUserAsync(User);
            return View(appUser);
        }
    }
}

src/src/Views/Config/AddEditIndex.cshtml
@model src.Models.Employees
@{
    Layout = null;
}
<style>

    .default {
        display: none;
    }
</style>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Edit dashboard</h4>
</div>

<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="IdNumber" />

    <div class="row">
        <div class="form-group col-lg-12">
            <label asp-for="FullName" class="control-label"></label>
            <input asp-for="FullName" class="form-control" readonly />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>
        
    </div>

    <div class="row">
        <div class="form-group col-lg-6">
            <label asp-for="BasicPay" class="control-label"></label>
            <input asp-for="BasicPay" class="form-control" />
            <span asp-validation-for="BasicPay" class="text-danger"></span>
        </div>
        <div class="form-group col-lg-6">
            <label asp-for="Role" class="control-label"></label>
            <select id="cars" asp-for="Role" class="form-control">
                <option selected disabled>Role...</option>
                <option value="Employee">Employee</option>
                <option value="Admin">Admin</option>
                <option value="Manager">Manager</option>
            </select>
            <span asp-validation-for="Role" class="text-danger"></span>
        </div>
    </div>

    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

src/src/Views/Config/AddEditOrganization.cshtml
@model src.Models.Organization
@{
    Layout = null;
}


<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Add / Edit Data</h4>
</div>
<form onsubmit="return SubmitAddEdit(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="organizationId" />
        <input type="hidden" asp-for="organizationOwnerId" />
        <div class="form-group">
            <label asp-for="organizationName" class="control-label"></label>
            <input asp-for="organizationName" class="form-control" />
            <span asp-validation-for="organizationName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="description" class="control-label"></label>
            <input asp-for="description" class="form-control" />
            <span asp-validation-for="description" class="text-danger"></span>
        </div>

    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>
<script>
    Ladda.bind('.btn', { timeout: 1000 });
</script>

src/src/Views/Config/Index.cshtml
@model src.Models.Organization
@inject UserManager<ApplicationUser> UserManager
@{
    ViewData["Title"] = "Dashboard";
    ApplicationUser appUser = await UserManager.GetUserAsync(User);
    if (appUser.Role == "Employee")
    {
        Layout = "_LayoutAdminlteEmployee";
    }
    if (appUser.Role == "Inactive")
    {
        Layout = "_LayoutAdminlteInactive";
    }
    else if (appUser.Role == "Admin")
    {
        Layout = "_LayoutAdminlteAdmin";
    }
    else if (appUser.Role == "Manager")
    {
        Layout = "_LayoutAdminlteManager";
    }
}

<!-- Content Header (Page header) -->
<!-- Main content -->
@if (appUser.Role == "Employee")
{
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @*<input type="hidden" asp-for="@Model.organizationId" />*@
                                <table id="grid" name="grid" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="col-md-1">Id</th>
                                            <th class="col-md-1">Name</th>
                                            @*<th class="col-md-1">Position</th>*@
                                            @*<th class="col-md-1">Basic pay</th>*@
                                            <th class="col-md-1">Cola</th>
                                            <th class="col-md-1">Role</th>
                                            <th class="col-md-1">Days worked</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

        </div>

    </section>
}
else if (appUser.Role == "Admin")
{
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @*<input type="hidden" asp-for="@Model.organizationId" />*@
                                <table id="grid" name="grid" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="col-md-1">Id</th>
                                            <th class="col-md-1">Name</th>
                                            @*<th class="col-md-1">Position</th>*@
                                            <th class="col-md-1">Basic pay</th>
                                            <th class="col-md-1">Cola</th>
                                            <th class="col-md-1">Role</th>
                                            <th class="col-md-1">Days worked</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </section>
}

else if (appUser.Role == "Manager")
{
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <div class="box box-primary">
                    <div class="box-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @*<input type="hidden" asp-for="@Model.organizationId" />*@
                                <table id="grid" name="grid" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th class="col-md-1">Id</th>
                                            <th class="col-md-1">Name</th>
                                            @*<th class="col-md-1">Position</th>*@
                                            <th class="col-md-1">Basic pay</th>
                                            <th class="col-md-1">Cola</th>
                                            <th class="col-md-1">Role</th>
                                            <th class="col-md-1">Days worked</th>
                                            <th class="col-md-1">Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>

    </section>
}

<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    @if (appUser.Role == "Employee")
    {
        <script src="~/js/views/dashboard/employee.js"></script>
    }
    else if (appUser.Role == "Admin")
    {
        <script src="~/js/views/dashboard/admin.js"></script>
    }
    else if (appUser.Role == "Manager")
    {
        <script src="~/js/views/dashboard/index.js"></script>
    }

}

src/src/Views/Config/Organization.cshtml
@model src.Models.ApplicationUser
@{
    ViewData["Title"] = "Organization";
    Layout = "_LayoutAdminlteNoMenu";
}

<!-- Content Header (Page header) -->
<!-- Main content -->
<section class="content">
    <input type="hidden" asp-for="@Model.Id" />
    <div class="row">
        <div class="col-lg-9">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <table id="gridOrganization" name="gridOrganization" class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th class="col-md-8">Organization</th>
                                        <th class="col-md-4"></th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-3">
            <div class="row">
                <div class="col-md-12">
                    <a class="btn btn-success" style="margin-bottom:10px" onclick="ShowPopup('@Url.Action("AddEditOrganization","Config")')"><i class="fa fa-plus"></i> Add New Organization</a>
                </div>
            </div>
        </div>
    </div>

</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>



@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/js/views/config/index.js"></script>
}

src/src/Views/Config/PersonalProfile.cshtml
@model ApplicationUser
@{
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Change Personal Profile Data</h4>
</div>
<form onsubmit="return ChangePersonalProfile(this)">
    <div class="box-body">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="FullName"></label>
            <input asp-for="FullName" class="form-control" />
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="BirthDate"></label>
            <input asp-for="BirthDate" class="form-control" />
            <span asp-validation-for="BirthDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PhoneNumber"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

    </div>

    <div class="box-footer">
        <button type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i> Submit</button>
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button>
    </div>
</form>

src/src/Views/Config/UserProfile.cshtml
@model src.Models.ApplicationUser
@inject UserManager<ApplicationUser> UserManager
@inject src.Data.ApplicationDbContext Context
@{
    ViewData["Title"] = "UserProfile";
    ApplicationUser appUser = await UserManager.GetUserAsync(User);
    @if (appUser.Role == "Employee")
    {
        Layout = "~/Views/Shared/_LayoutAdminlteEmployee.cshtml";
    }
     else if (appUser.Role == "Admin")
    {
        Layout = "~/Views/Shared/_LayoutAdminlteAdmin.cshtml";
    }
    else if (appUser.Role == "Manager")
    {
        Layout = "~/Views/Shared/_LayoutAdminlteManager.cshtml";
    }
}

<!-- Main content -->
<section class="content">
    <div class="row">

        <!-- /.col -->
        <div class="col-md-12">
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">

                    <li class="active"><a href="#editProfile" data-toggle="tab">Edit Profile</a></li>
                    <li><a href="#changePassword" data-toggle="tab">Change Password</a></li>
                </ul>
                <div class="tab-content">

                    <!-- /.tab-pane -->
                    <div class="active tab-pane" id="editProfile">
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h4>Change Your Personal Profile Data</h4>

                            </div>
                            <div class="icon">
                                <i class="ion ion-person"></i>
                            </div>

                            <a onclick="ShowPopup('@Url.Action("PersonalProfile","Config")')" class="btn small-box-footer">Open Personal Profile Form <i class="fa fa-gear"></i></a>
                        </div>
                    </div>
                    <!-- /.tab-pane -->
                    <div class="tab-pane" id="changePassword">
                        <div class="small-box bg-green">
                            <div class="inner">
                                <h4>Change Old Password With The New Password</h4>

                            </div>
                            <div class="icon">
                                <i class="ion ion-key"></i>
                            </div>

                            <a onclick="ShowPopup('@Url.Action("ChangePassword","Manage")')" class="btn small-box-footer">Open Change Password Form <i class="fa fa-gear"></i></a>
                        </div>

                    </div>
                    <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script src="~/js/views/config/userprofile.js"></script>

}

src/src/Views/Config/UserUploadPhoto.cshtml
@model src.Models.ApplicationUser
@inject src.Data.ApplicationDbContext Context
@{
    ViewData["Title"] = "Upload Photo";
    Layout = "~/Views/Shared/_LayoutAdminlteNoMenu.cshtml";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <!-- Profile Image -->
            <div class="box box-primary">
                <div class="box-body box-profile">
                    <img id="profilePicture" class="profile-user-img img-responsive img-circle" src="../@Model.ProfilePictureUrl" alt="User profile picture">
                    <h3 class="profile-username text-center"><span class="profile-fullName">@Model.FullName</span></h3>
                    @if (Model.Role == "Manager")
                    {
                        <p class="text-muted text-center">Manager</p>
                    }
                    else if (Model.Role == "Admin")
                    {
                        <p class="text-muted text-center">Admin</p>
                    }
                    else if (Model.Role == "Employee")
                    {
                        <p class="text-muted text-center">Employee</p>
                    }


                    <ul class="list-group list-group-unbordered">
                        <li class="list-group-item text-center">
                            <span class="btn btn-success fileinput-button">
                                <i class="fa fa-camera bg-green"></i>
                                <span>Select file ...</span>
                                <!-- The file input field used as target for the file upload widget -->
                                <input id="fileupload" type="file" name="files" multiple="">
                            </span>

                        </li>
                        <li class="list-group-item">
                            <div id="progress" class="progress">
                                <div class="progress-bar progress-bar-success"></div>
                            </div>
                        </li>

                    </ul>

                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->

        </div>
        <!-- /.col -->
        
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
<!--modal placeholder-->
<div class="modal modal-primary fade" id="modalDefault">
    <div class="modal-dialog">
        <div class="modal-content">

        </div>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial")

    <script src="~/js/views/config/userprofile.js"></script>

}